name: lightspot_v1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # -- map & clustering
  google_maps_flutter: ^2.12.0          # ‚Üê pinned, no ^
  google_maps_cluster_manager_2: ^3.2.0

  # -- ui
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1

  # -- networking
  http: ^1.1.0

  # -- other
  nav: ^1.4.3
  injectable: ^2.5.0
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  meta: ^1.15.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner: ^2.4.14
  shared_preferences: ^2.3.2
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/pins/location-pin.png # your red pin
    - assets/pins/2.0x/location-pin.png
    - assets/pins/3.0x/location-pin.png